language: python

python:
  - "3.5"
  - "3.6"

install:
  - "pip install -r requirements.txt"

script:
  - python -m unittest discover -v -s exodus_core -p "test_*.py"
  - python setup.py sdist

notifications:
  email:
    recipients:
      - u039b@exodus-privacy.eu.org
    on_success: always
    on_failure: always

deploy:
  provider: releases
  api_key: "520282bbf8d763db275a0b3cb676466e1330d5a2"
  file:
    - dist/*.tar.gz
  file_glob: true
  on:
    repo: Exodus-Privacy/exodus-core
    tags: true
skip_cleanup: true